all: task4_2 task4_3

task4_2:
	gcc -I/home/seed/openssl-1.0.1/include -o task4_2 50_Shuo_Yang_Task4_2.c -L/home/seed/openssl-1.0.1/ -lcrypto -ldl

task4_3:
	gcc -I/home/seed/openssl-1.0.1/include -o task4_3 50_Shuo_Yang_Task4_3.c -L/home/seed/openssl-1.0.1/ -lcrypto -ldl

clean:
	rm task4_2 task4_3
