create table azmet (
       station varchar(50),
       year integer,
       day_of_year integer,
       month integer,
       day_of_month integer,
       station_num integer,
       air_temp_max float,
       air_temp_min float,
       air_temp_mean float,
       rh_max float,
       rh_min float,
       rh_mean float,
       vpd_mean float,
       solar_rad_total float,
       precipitation_total float,
       soil_temp_4_max float,
       soil_temp_4_min float,
       soil_temp_4_mean float,
       soil_temp_20_max float,
       soil_temp_20_min float,
       soil_temp_20_mean float,
       wind_speed_mean float,
       wind_vector_magnitude_mean float,
       wind_vector_direction_mean float,
       wind_direction_stddev float,
       max_wind_speed float,
       heat_units float,
       eto float,
       etos float,
       actual_vapor_pressure float,
       dewpoint float,
       primary key (station, year, day_of_year)
);

commit;
